// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNJ6gA_MIPteZiIa2Pkgd4TeIVIuNGaVI',
    appId: '1:166699712370:web:40d6b5f4edc4abf893e7eb',
    messagingSenderId: '166699712370',
    projectId: 'demoapp-8e52b',
    authDomain: 'demoapp-8e52b.firebaseapp.com',
    storageBucket: 'demoapp-8e52b.appspot.com',
    measurementId: 'G-5G9WFFJTS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqNZrnyVA--nSoQWERdIB9_bOEkTvVi4',
    appId: '1:166699712370:android:5e2108343a13ab6f93e7eb',
    messagingSenderId: '166699712370',
    projectId: 'demoapp-8e52b',
    storageBucket: 'demoapp-8e52b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnErJ5pxjL3gtvdwpR9FLc-RJ58vicbpU',
    appId: '1:166699712370:ios:cf63b5ce206ee36493e7eb',
    messagingSenderId: '166699712370',
    projectId: 'demoapp-8e52b',
    storageBucket: 'demoapp-8e52b.appspot.com',
    iosBundleId: 'com.example.firebaeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnErJ5pxjL3gtvdwpR9FLc-RJ58vicbpU',
    appId: '1:166699712370:ios:cf63b5ce206ee36493e7eb',
    messagingSenderId: '166699712370',
    projectId: 'demoapp-8e52b',
    storageBucket: 'demoapp-8e52b.appspot.com',
    iosBundleId: 'com.example.firebaeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNJ6gA_MIPteZiIa2Pkgd4TeIVIuNGaVI',
    appId: '1:166699712370:web:f1d6c50e5994342e93e7eb',
    messagingSenderId: '166699712370',
    projectId: 'demoapp-8e52b',
    authDomain: 'demoapp-8e52b.firebaseapp.com',
    storageBucket: 'demoapp-8e52b.appspot.com',
    measurementId: 'G-0PGE6S90TD',
  );
}
